import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f8f5ee',
  },
  gridBackground: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#f8f5ee',
  },
  gridLineVertical: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 1,
    backgroundColor: '#e4e0dc',
  },
  gridLineHorizontal: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: '#e4e0dc',
  },
  container: {
    paddingHorizontal: 20,
    paddingTop: 34,
    paddingBottom: 90,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginBottom: 30,
  },
  headerTextBox: {
    flex: 1,
    paddingRight: 14,
  },
  eyebrow: {
    color: '#776f66',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 3,
  },
  bigTitle: {
    color: '#111111',
    fontSize: 58,
    fontWeight: '900',
    lineHeight: 62,
  },
  subtitle: {
    color: '#776f66',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
    maxWidth: 320,
  },
  headerActionBox: {
    alignItems: 'center',
    gap: 10,
  },
  headerCount: {
    color: '#776f66',
    fontSize: 13,
    fontWeight: '600',
  },
  plusButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#eee7dc',
    alignItems: 'center',
    justifyContent: 'center',
  },
  plusText: {
    color: '#111111',
    fontSize: 28,
    fontWeight: '500',
    marginTop: -2,
  },
  statsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 36,
    gap: 12,
  },
  folderWrapper: {
    marginBottom: 18,
  },
  folderSmallWrapper: {
    flex: 1,
  },
  folderTab: {
    height: 21,
    width: '42%',
    marginLeft: 13,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  folderTabSmall: {
    height: 18,
    width: '48%',
    marginLeft: 10,
  },
  folderBody: {
    borderTopRightRadius: 28,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    padding: 20,
    shadowColor: '#000000',
    shadowOpacity: 0.16,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
    elevation: 6,
  },
  folderBodySmall: {
    paddingVertical: 16,
    paddingHorizontal: 12,
    minHeight: 92,
    justifyContent: 'center',
  },
  statNumber: {
    color: '#151515',
    fontSize: 36,
    lineHeight: 40,
    fontWeight: '900',
  },
  statLabel: {
    color: '#151515',
    opacity: 0.78,
    fontSize: 14,
    fontWeight: '700',
    marginTop: 2,
  },
  formTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
    marginBottom: 12,
  },
  sectionTitle: {
    color: '#111111',
    fontSize: 30,
    fontWeight: '900',
  },
  selectedPriorityBadge: {
    overflow: 'hidden',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    fontSize: 12,
    fontWeight: '800',
  },
  formCard: {
    backgroundColor: '#ffffff',
    borderRadius: 28,
    padding: 20,
    marginBottom: 44,
    shadowColor: '#000000',
    shadowOpacity: 0.11,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  input: {
    backgroundColor: '#eee7dc',
    borderRadius: 14,
    minHeight: 50,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: '#111111',
    fontSize: 16,
    marginBottom: 12,
  },
  descriptionInput: {
    minHeight: 92,
    textAlignVertical: 'top',
  },
  inputLabel: {
    color: '#776f66',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 9,
    marginTop: 4,
  },
  categoryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  categoryButton: {
    backgroundColor: '#eee7dc',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  categoryButtonText: {
    color: '#756d63',
    fontSize: 14,
    fontWeight: '700',
  },
  selectedText: {
    color: '#111111',
  },
  priorityRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 18,
  },
  priorityButton: {
    flex: 1,
    backgroundColor: '#eee7dc',
    borderRadius: 14,
    alignItems: 'center',
    paddingVertical: 12,
  },
  priorityButtonText: {
    color: '#756d63',
    fontSize: 14,
    fontWeight: '800',
  },
  priorityHigh: {
    backgroundColor: '#f6d4d0',
    color: '#c94537',
  },
  priorityMedium: {
    backgroundColor: '#f9e8b9',
    color: '#9b6428',
  },
  priorityLow: {
    backgroundColor: '#d8f0e3',
    color: '#2f7e55',
  },
  addButton: {
    height: 52,
    borderRadius: 14,
    backgroundColor: '#111111',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addButtonText: {
    color: '#f7f2e9',
    fontSize: 16,
    fontWeight: '800',
  },
  taskListTitleRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
    marginBottom: 14,
  },
  taskListTitle: {
    color: '#111111',
    fontSize: 40,
    fontWeight: '900',
  },
  recordCount: {
    color: '#776f66',
    fontSize: 14,
    fontWeight: '600',
  },
  filterContainer: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    backgroundColor: '#eee7dc',
    borderRadius: 999,
    padding: 4,
    marginBottom: 22,
  },
  filterButton: {
    borderRadius: 999,
    paddingHorizontal: 15,
    paddingVertical: 9,
  },
  filterButtonActive: {
    backgroundColor: '#111111',
  },
  filterButtonText: {
    color: '#756d63',
    fontSize: 14,
    fontWeight: '800',
  },
  filterButtonTextActive: {
    color: '#f7f2e9',
  },
  taskMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  taskCategory: {
    color: '#222222',
    opacity: 0.72,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  activeBadge: {
    overflow: 'hidden',
    backgroundColor: '#ffffff99',
    color: '#111111',
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 4,
    fontSize: 11,
    fontWeight: '800',
  },
  doneBadge: {
    overflow: 'hidden',
    backgroundColor: '#111111dd',
    color: '#f7f2e9',
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 4,
    fontSize: 11,
    fontWeight: '800',
  },
  taskTitle: {
    color: '#111111',
    fontSize: 25,
    lineHeight: 29,
    fontWeight: '900',
  },
  completedTitle: {
    textDecorationLine: 'line-through',
    opacity: 0.55,
  },
  taskDescription: {
    color: '#222222',
    opacity: 0.72,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
  },
  priorityBadge: {
    alignSelf: 'flex-start',
    overflow: 'hidden',
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 5,
    fontSize: 11,
    fontWeight: '800',
    marginTop: 13,
  },
  taskActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 18,
  },
  taskMainButton: {
    flex: 1,
    height: 42,
    borderRadius: 14,
    backgroundColor: '#ffffffcc',
    alignItems: 'center',
    justifyContent: 'center',
  },
  taskMainButtonText: {
    color: '#111111',
    fontSize: 14,
    fontWeight: '800',
  },
  taskDeleteButton: {
    minWidth: 58,
    height: 42,
    borderRadius: 14,
    backgroundColor: '#11111118',
    alignItems: 'center',
    justifyContent: 'center',
  },
  taskDeleteButtonText: {
    color: '#111111',
    fontSize: 14,
    fontWeight: '800',
  },
  emptyCard: {
    backgroundColor: '#ffffff',
    borderRadius: 28,
    paddingVertical: 44,
    paddingHorizontal: 22,
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  emptyIcon: {
    width: 58,
    height: 58,
    borderRadius: 18,
    backgroundColor: '#eee7dc',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  emptyIconText: {
    color: '#776f66',
    fontSize: 30,
    marginTop: -5,
  },
  emptyTitle: {
    color: '#111111',
    fontSize: 24,
    fontWeight: '900',
  },
  emptyText: {
    color: '#776f66',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    marginTop: 5,
  },
});
